-- hds header_start
--
-- VHDL Architecture final_lab.mk_alu.alu
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 22:55:25 05/24/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY final_lab;
USE final_lab.in_states.all;


ENTITY mk_alu IS
   PORT( 
      inA     : IN     std_logic_vector (7 DOWNTO 0);
      inPSW   : IN     std_logic_vector (7 DOWNTO 0);
      inTemp  : IN     std_logic_vector (7 DOWNTO 0);
      state   : IN     st_alu;
      compare : OUT    std_logic;
      output8 : OUT    std_logic_vector (7 DOWNTO 0);
      rd      : IN     std_logic;
      clk     : IN     std_logic
   );

-- Declarations

END mk_alu ;

-- hds interface_end
ARCHITECTURE alu OF mk_alu IS
begin
  process (clk) is
    variable reg : std_logic_vector(7 downto 0) := "00000000";
  begin
    if clk = '1' and clk'event then
      if(inA = inTemp) then
        compare <= '1';
      else
        compare <= '0';
      end if;
      case state is
        when Rn_addr => reg:="000" & inPSW(4 downto 3) & inTemp(2 downto 0);
        when rep => reg:=inTemp;
        when NOP => reg:=reg;
          
        when s_add => 
              reg:= f(inA , inTemp);
        when others => reg:=reg;
      end case;
      if(rd = '1') then
         output8 <= reg;
      else
         output8 <= (others => 'Z');
      end if;
    end if;
  end process;
END alu;
