--
-- VHDL Package Header final_lab.in_states
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 22:39:01 05/24/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

PACKAGE in_states IS

function f (A, B : IN     std_logic_vector (7 DOWNTO 0)) return std_logic_vector;
    type st_alu is (
                    NOP, Rn_addr, rep, s_add
                    );
    type st_uu is (
                    rs1, rs2, rs3, ex, 
--------------------------------------------------                   
                    l_com_1, l_com_2, l_com_3, l_com_4, 
--------------------------------------------------                    
                    mov_a_rn_1, mov_a_rn_2, mov_a_rn_3, mov_a_rn_4, 
                    mov_a_rn_5, mov_a_rn_6, mov_a_rn_7, 
--------------------------------------------------                                        
                    mov_rn_dir_0, mov_rn_dir_6_1,
                    mov_rn_dir_1, mov_rn_dir_2, mov_rn_dir_3, mov_rn_dir_4, 
                    mov_rn_dir_5, mov_rn_dir_6, mov_rn_dir_7, mov_rn_dir_8,
                    mov_rn_dir_9, mov_rn_dir_10, mov_rn_dir_11, mov_rn_dir_12,
--------------------------------------------------          
                    cjne_A_direct_1, cjne_A_direct_2, cjne_A_direct_3, cjne_A_direct_4,
                    cjne_A_direct_5, cjne_A_direct_6, cjne_A_direct_7, cjne_A_direct_8, 
                    cjne_A_direct_9, cjne_A_direct_10, cjne_A_direct_11, cjne_A_direct_12,
                    cjne_A_direct_13, cjne_A_direct_14, cjne_A_direct_15 
                   );
END in_states;
