-- hds header_start
--
-- VHDL Architecture final_lab.mk_pc.pc
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 23:37:22 05/23/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;


ENTITY mk_pc IS
   PORT( 
      HL        : IN     std_logic;
      clk       : IN     std_logic;
      inc       : IN     std_logic;
      rd        : IN     std_logic;
      res       : IN     std_logic;
      wr        : IN     std_logic;
      pc_out16  : OUT    std_logic_vector (15 DOWNTO 0);
      pc_inout8 : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END mk_pc ;

-- hds interface_end
ARCHITECTURE pc OF mk_pc IS
     signal reg : std_logic_vector(15 downto 0) := "0000000000000000";
BEGIN
  process (clk) is
  begin
    if clk = '1' and clk'event then
      if(res = '1') then
        reg <= (others => '0');
      elsif(wr = '1') then
        if(HL = '1') then
          reg(15 downto 8) <= pc_inout8;
        elsif(HL = '0') then
          reg(7 downto 0) <= pc_inout8;
        end if;
      elsif(inc = '1') then
        reg <= reg + 1;      
      end if;
      if(rd = '1') then
        if(HL = '1') then
          pc_inout8 <= reg(15 downto 8);
        elsif(HL = '0') then
          pc_inout8 <= reg(7 downto 0);
        end if;
      else
        pc_inout8 <= (others => 'Z');
      end if;
    end if;   
  end process;
  pc_out16 <= reg;

END pc;
