-- hds header_start
--
-- VHDL Architecture final_lab.mk_reg1.reg1
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 23:20:24 05/24/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY final_lab;
USE final_lab.in_states.all;

ENTITY mk_reg1 IS
   PORT( 
      Wr     : IN     std_logic;
      clk    : IN     std_logic;
      input  : IN     std_logic_vector (7 DOWNTO 0);
      output : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END mk_reg1 ;

-- hds interface_end
ARCHITECTURE reg1 OF mk_reg1 IS
signal reg : std_logic_vector(7 downto 0) := "00000000";
begin
   process (clk) is
   begin
       if(clk='1' and clk'event) then
          if(Wr = '1') then
              reg <= input;
          end if;
       end if;
   end process;
   output <= reg;
END reg1;
