-- hds header_start
--
-- VHDL Architecture final_lab.tb.tb
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 01:25:52 05/25/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY final_lab;
USE final_lab.in_states.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_textio.ALL;
LIBRARY std;
USE std.textio.ALL;

ENTITY tb IS
   PORT( 
      clk : OUT    std_logic;
      rst : OUT    std_logic
   );

-- Declarations

END tb ;

-- hds interface_end
ARCHITECTURE tb OF tb IS

signal clock: std_logic:= '0';
signal reset: std_logic:= '0';

BEGIN
   clock <= not clock after 3 ns;
   clk <= clock;
   reset <= '1', '0' after 1 ns;
   rst <= reset;

END tb;
