-- hds header_start
--
-- VHDL Architecture final_lab.temp_mux.mux
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 19:57:58 05/28/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY temp_mux IS
   PORT( 
      clk     : IN     std_logic;
      comm    : IN     std_logic_vector (7 DOWNTO 0);
      ram     : IN     std_logic_vector (7 DOWNTO 0);
      sel     : IN     std_logic;
      mux_res : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END temp_mux ;

-- hds interface_end
ARCHITECTURE mux OF temp_mux IS
BEGIN

process(clk) is
begin
	if clk = '1' and clk'event then
		if sel = '0' then
			mux_res <= comm;
		else
			mux_res <= ram;
		end if;
	end if;
end process;
END mux;
