-- hds header_start
--
-- VHDL Architecture final_lab.mk_reg2.reg2
--
-- Created:
--          by - Y50-70.UNKNOWN (LENOVO)
--          at - 23:23:34 05/24/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1a (Build 22)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY mk_reg2 IS
   PORT( 
      clk    : IN     std_logic;
      rd     : IN     std_logic;
      wr     : IN     std_logic;
      output : OUT    std_logic_vector (7 DOWNTO 0);
      input  : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END mk_reg2 ;

-- hds interface_end
ARCHITECTURE reg2 OF mk_reg2 IS
 signal reg : std_logic_vector(7 downto 0) := "00000000";
begin
  process (clk) is
    begin
    if clk='1' and clk'event then
      if(rd = '1') then
        input <= reg;
	  end if;
      if rd = '0' and wr = '0' then
        input <= (others => 'Z');  
      end if;
      if(wr = '1') then
        reg <= input;
      end if;          
    end if;
   end process;
   output <= reg; 
END reg2;
